import { theme } from '../components/Theme';

const styles = {
  nav: {
    width: '100%',
    height: '5rem',
    background:
      'transparent linear-gradient(180deg, rgba(255, 255, 255, 0.5) 0%, rgba(255, 255, 255, 0.5) 100%)',
    opacity: 1,
    webkitBackdropFilter: 'blur(6px)',
    mozBackdropFilter: 'blur(6px)',
    backdropFilter: 'blur(6px)',
  },
  navButton: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: '#0d2344',
    height: '3rem',
    width: '7rem',
    borderRadius: '.5rem',
    margin: '0 1rem',
    transition: '0.5s all ease-out',
    '&:hover': {
      color: theme.palette.primary.main,
      background: 'rgba(255, 166, 0, 0.2)',
      backdropFilter: 'blur(6px)',
      boxShadow: '-2px 2px 5px 2px rgba(0, 0, 0, 0.1)',
    },
  },
  navActionButton: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: theme.palette.secondary.main,
    height: '3rem',
    width: '6rem',
    borderRadius: '.5rem',
    padding: '0 .5rem',
    margin: '0 .5rem',
    transition: '0.5s all ease-out',
    '&:hover': {
      color: '#ffffff',
      background: 'rgba(14, 83, 148, 1)',
      backdropFilter: 'blur(6px)',
      boxShadow: '-2px 2px 5px 2px rgba(0, 0, 0, 0.3)',
    },
  },
  specialty: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '3rem',
    borderRadius: '1rem',
  },
  specialty_icon: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '3.5rem',
    height: '3.5rem',
    borderRadius: '50%',
  },
  plans: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '1rem',
    margin: '1rem 0',
    borderRadius: '1rem',
    width: '10rem',
  },
  plans_icon: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '3.5rem',
    height: '3.5rem',
    borderRadius: '50%',
  },
  services_icon: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '3.5rem',
    height: '3.5rem',
    borderRadius: '1rem',
    background: '#f5f5f5',
  },
  footer_icon: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '2rem',
    height: '2rem',
    borderRadius: '50%',
    background: '#FEF9F1',
  },

  menu_icon_bg: {
    position: 'absolute',
    left: '0',
    width: '2.5rem',
    height: '2.5rem',
    borderRadius: '50%',
    background: '#fcf0e8',
    margin: '0 0 0 .5rem',
    zIndex: 0,
  },

  menu_icon: {
    position: 'absolute',
    top: '1.5rem',
    left: '1rem',
  },

  relativeContainer: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
  },

  main_submenu: {
    position: 'absolute',
    left: '1rem',
    width: '20rem',
    background: '#fff',
    borderRadius: '.5rem',
    margin: '0',
    overflow: 'hidden',
    boxShadow: '0px 4px 25px 1px rgba(0,0,0,0.10)',
  },

  menu_listitem: {
    display: 'flex',
    justifyContent: 'center',
    overflow: 'hidden',
    height: '6rem',
    width: { sm: '55%', md: '100%' },
  },

  mobileSubmenu: {
    left: '3rem',
    top: '10rem',
    width: '20rem',
    background: '#fff',
    borderRadius: '.5rem',
    margin: '0',
    overflow: 'hidden',
    boxShadow: '0px 4px 25px 1px rgba(0,0,0,0.10)',
    zIndex: 1000,
  },

  divider: {
    width: '5%',
    height: '.2rem',
    margin: '.5rem 0',
    background: '#ffa500',
    borderRadius: '50%',
  },

  // Login page
  loginContainer: {
    margin: '-10rem 0 0 0',
    width: '100%',
    height: '100vh',
    backgroundImage: `url(/doctor-and-patient.jpg)`,
    backgroundSize: 'cover',
    backdropFilter: 'blur(6px)',
    overflow: 'hidden',
  },
  loginTransbox: {
    position: 'absolute',
    width: '100%',
    height: '100vh',
    top: '0',
    left: '0',
    backdropFilter: 'blur(1px)',
    background: 'rgba(1, 1, 1, 0.5)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    perspective: '1000px',
  },
  loginForm: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    height: '90vh',
    transition: 'transform 0.8s',
    transformStyle: 'preserve-3d',
  },
  loginFormList: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  
  // Signup page
  signupContainer: {
    margin: '-10rem 0 0 0',
    width: '100%',
    height: '100vh',
    backgroundImage: `url(/doctor.png)`,
    backgroundSize: 'cover',
    backdropFilter: 'blur(6px)',
    overflow: 'hidden',
  },
  signupTransbox: {
    position: 'absolute',
    width: '100%',
    height: '100vh',
    top: '0',
    left: '0',
    backdropFilter: 'blur(1px)',
    background: 'rgba(1, 1, 1, 0.5)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    perspective: '1000px',
  },
  signupForm: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    height: '90vh',
    transition: 'transform 0.8s',
    transformStyle: 'preserve-3d',
  },
  signupFormList: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    webkitBackfaceVisibility: 'hidden',
    backfaceVisibility: 'hidden'
  },
};

export { styles };
