const styles = {
  navButton: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: '#000000',
    height: '3rem',
    width: '7rem',
    borderRadius: '.5rem',
    margin: '0 1rem',
  },
  navActionButton: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: '#000000',
    height: '3rem',
    width: '6rem',
    borderRadius: '.5rem',
    padding: '0 .5rem',
    margin: '0 .5rem',
  },
  specialty: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '3rem',
    borderRadius: '1rem',
  },
  specialty_icon: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '3.5rem',
    height: '3.5rem',
    borderRadius: '50%',
  },
  plans: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '1rem',
    margin: '1rem 0',
    borderRadius: '1rem',
    width: '10rem',
  },
  plans_icon: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '3.5rem',
    height: '3.5rem',
    borderRadius: '50%',
  },
  services_icon: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '3.5rem',
    height: '3.5rem',
    borderRadius: '1rem',
    background: '#f5f5f5',
  },
  footer_icon: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '3rem',
    height: '3rem',
    borderRadius: '50%',
    background: '#FEF9F1',
  },
  divider: {
    width: '5%',
    height: '.2rem',
    margin: '.5rem 0',
    background: '#ffa500',
    borderRadius: '50%',
  },
};

export { styles };
